const API_BASE = window.location.hostname === 'localhost' || window.location.hostname === '127.0.0.1' ? 'http://localhost:3000/api' : 'https://html-css-3bew.onrender.com/api';
const STORAGE_KEYS = { cart: 'gutenberg-cart', user: 'gutenberg-user', session: 'gutenberg-session' };
const VIP_PLANS = { basico: { name: 'Básico', price: '29,90', description: 'Para começar um ritual mensal.', benefits: ['1 livro básico por mês', 'Notícias antecipadas', 'Vantagens do clube'] }, medio: { name: 'Médio', price: '49,90', description: 'Uma edição especial por mês.', benefits: ['1 livro de capa dura por mês', 'Chat exclusivo', 'Vantagens do clube'], featured: true }, avancado: { name: 'Avançado', price: '79,90', description: 'A experiência completa Gutenberg.', benefits: ['1 livro de capa dura', '1 combo todo mês', 'Todas as vantagens'] } };
const FALLBACK_BOOKS = [
  { id: 'fallback-book-1', titulo: 'Orgulho e Preconceito', descricao: 'Uma edição para voltar às ironias, encontros e desencontros de Jane Austen.', preco: 39.9, categoria: 'livro', genero: 'Clássicos', estoque: 12, amostra_primeira_pagina: 'É uma verdade universalmente reconhecida que um homem solteiro, possuidor de boa fortuna, deve estar necessitado de esposa.' },
  { id: 'fallback-book-2', titulo: 'Noites Brancas', descricao: 'O encontro breve e inesquecível de duas pessoas solitárias em São Petersburgo.', preco: 31.9, categoria: 'livro', genero: 'Literatura russa', estoque: 8, amostra_primeira_pagina: 'Era uma noite maravilhosa, uma dessas noites que só são possíveis quando somos jovens.' },
  { id: 'fallback-book-3', titulo: 'Memórias do Subsolo', descricao: 'Um clássico inquieto sobre consciência, liberdade e as contradições humanas.', preco: 35.9, categoria: 'livro', genero: 'Ficção', estoque: 5, amostra_primeira_pagina: 'Sou um homem doente... Sou um homem mau. Um homem desagradável.' },
  { id: 'fallback-book-4', titulo: 'A Metamorfose', descricao: 'A narrativa de Kafka sobre estranhamento, família e a condição de existir.', preco: 28.9, categoria: 'livro', genero: 'Clássicos', estoque: 15, promocao: true, preco_antigo: 35.9, amostra_primeira_pagina: 'Quando certa manhã Gregor Samsa acordou de sonhos intranquilos, encontrou-se transformado.' }
];
const FALLBACK_STATIONERY = [
  { id: 'fallback-stationery-1', titulo: 'Post-it', descricao: 'Blocos adesivos para ideias que não podem esperar.', preco: 12.9, categoria: 'papelaria', genero: 'Escritório', cor: 'Amarelo' },
  { id: 'fallback-stationery-2', titulo: 'Caneta Preta', descricao: 'Traço confortável para listas, cartas e anotações.', preco: 6.9, categoria: 'papelaria', genero: 'Escolar', cor: 'Preto' },
  { id: 'fallback-stationery-3', titulo: 'Caderno Simples', descricao: 'Capa flexível e páginas para começar qualquer projeto.', preco: 24.9, categoria: 'papelaria', genero: 'Artesanato', cor: 'Rosa' },
  { id: 'fallback-stationery-4', titulo: 'Kit Volta às Aulas', descricao: 'O essencial para estudar com mais cor e organização.', preco: 59.9, categoria: 'papelaria', genero: 'Kit', cor: 'Colorido' }
];
const LOCAL_PRODUCT_IMAGES = {
  'orgulho e preconceito': 'images/orgulho_e_preconceito.jpg',
  'noites brancas': 'images/noites_bracas.jpg',
  'memórias do subsolo': 'images/memorias_subsolo.jpg',
  'a metamorfose': 'images/a_metamorfose.jpg',
  'post-it': 'images/post_it.svg',
  'caneta preta': 'images/caneta_preta.svg',
  'caderno simples': 'images/caderno_simples.svg',
  'kit volta às aulas': 'images/kit_volta_as_aulas.svg'
};
const state = { user: readStorage(STORAGE_KEYS.user), cart: readStorage(STORAGE_KEYS.cart) || [], books: [], stationery: [], selectedProduct: null, reviews: [], activeChat: 'geral', messages: [], diaries: [], trechos: [], meusPedidos: [], adminPedidos: [], activePedidoId: null };
const $ = (selector, root = document) => root.querySelector(selector);
const $$ = (selector, root = document) => [...root.querySelectorAll(selector)];
function readStorage(key) { try { return JSON.parse(localStorage.getItem(key)); } catch (error) { console.error('Não foi possível ler o armazenamento local.', error); return null; } }
function saveStorage(key, value) { localStorage.setItem(key, JSON.stringify(value)); }
function escapeHtml(value = '') { const div = document.createElement('div'); div.textContent = String(value); return div.innerHTML; }
function formatPrice(value) { return Number(value || 0).toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' }); }
function formatDate(value) { if (!value) return ''; const date = new Date(value); return Number.isNaN(date.valueOf()) ? value : date.toLocaleDateString('pt-BR'); }
function toast(message) { const item = document.createElement('div'); item.className = 'toast'; item.textContent = message; $('#toastRegion').append(item); setTimeout(() => item.remove(), 3600); }
function normalizeProduct(product, index = 0) { const id = product.id ?? product.produto_id ?? `api-product-${index}`; const titulo = product.titulo ?? product.nome ?? product.title ?? 'Produto Gutenberg'; const imagem = product.imagem ?? product.image ?? product.imagem_url ?? LOCAL_PRODUCT_IMAGES[String(titulo).trim().toLowerCase()]; return { ...product, id, titulo, descricao: product.descricao ?? product.description ?? 'Uma escolha especial da curadoria Gutenberg.', preco: Number(product.preco ?? product.price ?? 0), categoria: String(product.categoria ?? product.category ?? 'livro').toLowerCase(), genero: product.genero ?? product.genre ?? 'Curadoria Gutenberg', estoque: product.estoque ?? product.stock, imagem, amostra_primeira_pagina: product.amostra_primeira_pagina ?? product.preview, promocao: Boolean(product.promocao ?? product.em_promocao), preco_antigo: product.preco_antigo ?? product.old_price, is_combo: Boolean(product.is_combo), fallback: Boolean(product.fallback || String(id).startsWith('fallback-')) }; }
function getAccessToken() { const session = readStorage(STORAGE_KEYS.session); return session?.access_token || null; }
async function apiRequest(path, options = {}) { const token = getAccessToken(); const response = await fetch(`${API_BASE}${path}`, { headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}), ...(options.headers || {}) }, ...options }); let data = null; try { data = await response.json(); } catch (_) {} if (!response.ok) throw new Error(data?.error || data?.message || `Erro ${response.status}`); return data; }

// ---------- Catálogo ----------
async function loadProducts() { try { const [books, stationery] = await Promise.all([apiRequest('/produtos?categoria=livro'), apiRequest('/produtos?categoria=papelaria')]); state.books = Array.isArray(books) && books.length ? books.map(normalizeProduct) : FALLBACK_BOOKS.map(normalizeProduct); state.stationery = Array.isArray(stationery) && stationery.length ? stationery.map(normalizeProduct) : FALLBACK_STATIONERY.map(normalizeProduct); if (!books?.length || !stationery?.length) showConnection('A API está disponível, mas ainda não possui catálogo. Exibindo uma seleção demonstrativa.'); } catch (error) { console.error('Falha ao carregar produtos.', error); state.books = FALLBACK_BOOKS.map(normalizeProduct); state.stationery = FALLBACK_STATIONERY.map(normalizeProduct); showConnection('Não foi possível conectar ao catálogo. Você está vendo uma seleção demonstrativa.'); } renderAllProducts(); }
function showConnection(message) { const bar = $('#connectionBar'); bar.textContent = message; bar.hidden = false; }
function productVisual(product) { if (product.imagem) return `<img src="${escapeHtml(product.imagem)}" alt="Capa ou imagem de ${escapeHtml(product.titulo)}" onerror="this.parentElement.innerHTML='<div class=\\'cover-art\\'>${escapeHtml(product.titulo)}</div>'">`; const classes = product.categoria === 'papelaria' ? 'cover-art stationery-art' : 'cover-art'; const variants = product.id.toString().slice(-1); return `<div class="${classes} ${variants === '2' ? 'alt' : variants === '3' ? 'light' : ''}">${escapeHtml(product.titulo)}</div>`; }
function productCard(product) { const stationery = product.categoria === 'papelaria'; return `<article class="product-card ${stationery ? 'stationery' : ''}"><div class="product-image">${product.promocao ? '<span class="badge">Oferta</span>' : ''}${productVisual(product)}</div><div class="card-body"><span class="card-kicker">${escapeHtml(product.genero || (stationery ? 'Papelaria' : 'Livro'))}${product.is_combo ? ' · Combo' : ''}</span><h3 class="card-title">${escapeHtml(product.titulo)}</h3><p class="card-meta">${product.estoque != null ? `${product.estoque} em estoque` : stationery && product.cor ? `Cor: ${escapeHtml(product.cor)}` : 'Curadoria Gutenberg'}</p><div class="card-footer"><strong class="price">${formatPrice(product.preco)}</strong><button class="mini-button" data-product="${escapeHtml(product.id)}">${stationery ? 'Ver e personalizar' : 'Ver detalhes'}</button></div></div></article>`; }
function renderAllProducts() { $('#featuredGrid').innerHTML = state.books.slice(0, 4).map(productCard).join(''); renderBooks(); renderStationery(); }
function renderBooks() { const search = ($('#bookSearch')?.value || '').toLowerCase(); const genre = $('#bookGenre')?.value || ''; const format = $('#bookFormat')?.value || ''; const promo = $('#bookPromo')?.checked; let list = state.books.filter(product => `${product.titulo} ${product.genero} ${product.descricao}`.toLowerCase().includes(search) && (!genre || product.genero === genre) && (!format || product.formato === format) && (!promo || product.promocao)); const sort = $('#bookSort')?.value; if (sort === 'price-low') list.sort((a, b) => a.preco - b.preco); if (sort === 'price-high') list.sort((a, b) => b.preco - a.preco); if (sort === 'name') list.sort((a, b) => a.titulo.localeCompare(b.titulo)); $('#bookGrid').innerHTML = list.length ? list.map(productCard).join('') : '<div class="empty-state">Não encontramos livros com esses filtros.</div>'; $('#bookCount').textContent = `${list.length} ${list.length === 1 ? 'título' : 'títulos'}`; $('#bookState').textContent = list.length ? 'Seleção atual' : 'Catálogo vazio'; }
function renderStationery(category = '') { const list = state.stationery.filter(product => !category || product.genero === category); $('#stationeryGrid').innerHTML = list.length ? list.map(productCard).join('') : '<div class="empty-state">Não encontramos itens nessa categoria.</div>'; $('#stationeryCount').textContent = `${list.length} itens`; }
function findProduct(id) { return [...state.books, ...state.stationery].find(product => String(product.id) === String(id)); }
async function openProduct(id) { let product = findProduct(id); if (!product) return; if (!product.fallback) { try { product = normalizeProduct(await apiRequest(`/produtos/${encodeURIComponent(id)}`)); } catch (error) { console.error('Falha ao carregar detalhe do produto.', error); } } state.selectedProduct = product; const detail = $('#productDetail'); detail.innerHTML = `<div class="product-detail"><div class="detail-art">${productVisual(product)}</div><div><span class="card-kicker">${escapeHtml(product.genero)}</span><h2>${escapeHtml(product.titulo)}</h2><p class="detail-description">${escapeHtml(product.descricao)}</p><div class="stars">★★★★★ <small class="muted">Avaliações da comunidade</small></div><div class="detail-price">${formatPrice(product.preco)}</div><p class="muted">${product.estoque != null ? `Estoque disponível: ${product.estoque}` : 'Disponível para encomenda'}</p><div class="detail-actions"><button class="button primary" data-add="${escapeHtml(product.id)}">Adicionar à sacola</button>${product.categoria === 'papelaria' ? '<button class="button secondary" data-customize>Personalizar</button>' : `<button class="button secondary" data-preview="${escapeHtml(product.id)}">Ler primeira página</button>`}</div>${product.is_combo ? `<div class="review-box" id="comboBox"><strong>Este combo inclui</strong><div id="comboItemsList"><span class="empty-state">Carregando itens do combo...</span></div></div>` : ''}<div class="review-box"><strong>Avaliações de compradores e da comunidade</strong><div id="reviews"><span class="empty-state">${product.fallback ? 'Avaliações aparecem quando este item existir no catálogo da API.' : 'Carregando avaliações...'}</span></div><form class="review-form" id="reviewForm"><input type="number" min="1" max="5" required placeholder="Nota (1 a 5)" aria-label="Nota"><input required placeholder="Compartilhe sua leitura" aria-label="Comentário"><button class="mini-button">Avaliar</button></form></div></div></div>`; $('#productModal').showModal(); if (!product.fallback) { loadReviews(product.id); if (product.is_combo) loadComboItems(product.id); } }
async function loadReviews(id) { try { const data = await apiRequest(`/avaliacoes/produto/${encodeURIComponent(id)}`); state.reviews = Array.isArray(data) ? data : []; renderReviews(); } catch (error) { console.error('Falha ao carregar avaliações.', error); $('#reviews').innerHTML = '<span class="empty-state">Avaliações indisponíveis no momento.</span>'; } }
function renderReviews() { const compradas = state.reviews.filter(r => r.foi_comprado); const naoCompradas = state.reviews.filter(r => !r.foi_comprado); const linha = review => `<div class="review" data-review-id="${escapeHtml(review.id)}"><span class="stars">${'★'.repeat(Number(review.nota) || 0)}</span> ${escapeHtml(review.profiles?.nome || 'Leitor Gutenberg')}<br>${escapeHtml(review.comentario)}${isOwnerUser() ? ` <button type="button" class="remove-item" data-review-remove="${escapeHtml(review.id)}">Remover</button>` : ''}</div>`; $('#reviews').innerHTML = state.reviews.length ? `<p class="muted" style="margin:0 0 6px;font-size:11px;text-transform:uppercase;font-weight:700">Quem comprou</p>${compradas.length ? compradas.map(linha).join('') : '<span class="empty-state">Ainda sem avaliações de quem comprou.</span>'}<p class="muted" style="margin:14px 0 6px;font-size:11px;text-transform:uppercase;font-weight:700">Comunidade (não comprou)</p>${naoCompradas.length ? naoCompradas.map(linha).join('') : '<span class="empty-state">Ainda sem avaliações da comunidade.</span>'}` : '<span class="empty-state">Seja a primeira pessoa a avaliar este produto.</span>'; }
async function loadComboItems(id) { try { const data = await apiRequest(`/produtos/${encodeURIComponent(id)}/combo-itens`); $('#comboItemsList').innerHTML = data.length ? data.map(item => `<div class="admin-row"><div><strong>${escapeHtml(item.produto?.titulo || 'Item do combo')}</strong><small>${item.quantidade}x · ${formatPrice(item.produto?.preco)}</small></div>${item.produto ? `<button class="mini-button" data-product="${escapeHtml(item.produto.id)}">Comprar separado</button>` : ''}</div>`).join('') : '<span class="empty-state">A composição deste combo ainda não foi cadastrada.</span>'; } catch (error) { console.error('Falha ao carregar itens do combo.', error); $('#comboItemsList').innerHTML = '<span class="empty-state">Não foi possível carregar os itens do combo.</span>'; } }

// ---------- Carrinho / Checkout (pedido real) ----------
function addToCart(id, customization = null) { const product = findProduct(id); if (!product) return; const key = `${id}-${JSON.stringify(customization || {})}`; const existing = state.cart.find(item => item.key === key); if (existing) existing.quantity += 1; else state.cart.push({ key, product: { id: product.id, titulo: product.titulo, preco: product.preco, categoria: product.categoria }, quantity: 1, customization }); saveStorage(STORAGE_KEYS.cart, state.cart); renderCart(); toast('Produto adicionado à sacola.'); }
function renderCart() { const count = state.cart.reduce((total, item) => total + item.quantity, 0); $('#cartCount').textContent = count; $('#cartItems').innerHTML = state.cart.length ? state.cart.map(item => `<div class="cart-line"><div><h3>${escapeHtml(item.product.titulo)}</h3><p>${item.customization ? `Personalizado: ${escapeHtml(Object.values(item.customization).filter(Boolean).join(', '))}` : 'Edição Gutenberg'}</p><div class="quantity"><button data-quantity="-1" data-key="${escapeHtml(item.key)}">−</button><span>${item.quantity}</span><button data-quantity="1" data-key="${escapeHtml(item.key)}">+</button><button class="remove-item" data-remove="${escapeHtml(item.key)}">Remover</button></div></div><strong>${formatPrice(item.product.preco * item.quantity)}</strong></div>`).join('') : '<div class="empty-state">Sua sacola está esperando uma boa história.</div>'; $('#cartTotal').textContent = formatPrice(state.cart.reduce((total, item) => total + item.product.preco * item.quantity, 0)); }
function openCart() { $('#cartDrawer').classList.add('open'); $('#drawerOverlay').classList.add('open'); $('#cartDrawer').setAttribute('aria-hidden', 'false'); }
function closeCart() { $('#cartDrawer').classList.remove('open'); $('#drawerOverlay').classList.remove('open'); $('#cartDrawer').setAttribute('aria-hidden', 'true'); }
async function checkout() { if (!state.user?.id) { toast('Entre na sua conta para fechar o pedido.'); location.hash = '#login'; closeCart(); return; } if (!state.cart.length) { toast('Sua sacola está vazia.'); return; } const itens = state.cart.filter(item => !String(item.product.id).startsWith('fallback-')).map(item => ({ produto_id: item.product.id, quantidade: item.quantity, personalizacao: item.customization || null })); if (!itens.length) { toast('Os itens da sacola são de demonstração e ainda não existem na API.'); return; } try { const data = await apiRequest('/pedidos', { method: 'POST', body: JSON.stringify({ itens }) }); state.cart = []; saveStorage(STORAGE_KEYS.cart, state.cart); renderCart(); closeCart(); toast('Pedido realizado com sucesso!'); location.hash = '#perfil'; await loadMeusPedidos(); } catch (error) { console.error('Falha ao fechar pedido.', error); toast(error.message || 'Não foi possível fechar o pedido.'); } }

// ---------- Autenticação ----------
async function submitLogin(event) { event.preventDefault(); try { const data = await apiRequest('/auth/login', { method: 'POST', body: JSON.stringify({ email: $('#loginEmail').value, password: $('#loginPassword').value }) }); state.user = data.perfil ? { ...data.perfil, id: data.session?.user?.id || data.user?.id } : data.user; saveStorage(STORAGE_KEYS.user, state.user); if (data.session) saveStorage(STORAGE_KEYS.session, data.session); updateAccount(); toast('Login realizado com sucesso.'); location.hash = '#perfil'; } catch (error) { console.error('Falha no login.', error); toast(error.message || 'Não foi possível realizar o login.'); } }
async function submitAdminLogin(event) { event.preventDefault(); try { const data = await apiRequest('/auth/login', { method: 'POST', body: JSON.stringify({ email: $('#adminLoginEmail').value, password: $('#adminLoginPassword').value }) }); const profile = data.perfil ? { ...data.perfil, id: data.session?.user?.id || data.user?.id } : null; if (!profile || !isAdminRole(profile.tipo_usuario)) { toast('Esta conta não possui acesso administrativo.'); return; } state.user = profile; saveStorage(STORAGE_KEYS.user, state.user); if (data.session) saveStorage(STORAGE_KEYS.session, data.session); $('#adminLoginForm').reset(); $('#adminLoginModal').close(); updateAccount(); toast(`Login administrativo como ${adminRoleLabel(profile.tipo_usuario)} realizado.`); location.hash = '#admin'; } catch (error) { console.error('Falha no login administrativo.', error); toast(error.message || 'Não foi possível entrar no painel.'); } }
async function submitRegister(event) { event.preventDefault(); try { const data = await apiRequest('/auth/cadastrar', { method: 'POST', body: JSON.stringify({ email: $('#registerEmail').value, password: $('#registerPassword').value, nome: $('#registerName').value, tipo_usuario: 'cliente', plano_vip: $('#registerPlan').value }) }); state.user = data.user ? { id: data.user.id, nome: $('#registerName').value, email: data.user.email } : null; if (state.user) { saveStorage(STORAGE_KEYS.user, state.user); if (data.session) saveStorage(STORAGE_KEYS.session, data.session); updateAccount(); } toast('Cadastro realizado com sucesso.'); location.hash = state.user ? '#perfil' : '#login'; } catch (error) { console.error('Falha no cadastro.', error); toast(error.message || 'Não foi possível criar o cadastro.'); } }
function updateAccount() { $('#accountLink').textContent = state.user ? (state.user.nome || 'Perfil') : 'Entrar'; $('#accountLink').href = state.user ? '#perfil' : '#login'; if (state.user) { $('#profileTitle').textContent = `Olá, ${state.user.nome || 'leitor'}`; $('#profileSubtitle').textContent = state.user.email || 'Sua conta Gutenberg'; $('#profileContent').innerHTML = `<div class="profile-card"><strong>${state.books.length}</strong><span>livros na curadoria</span></div><div class="profile-card"><strong>${state.cart.length}</strong><span>itens na sacola</span></div><div class="profile-card"><strong>${state.user.plano_vip && state.user.plano_vip !== 'nenhum' ? 'VIP' : '—'}</strong><span>plano Gutenberg</span></div>`; } renderAdmin(); }

// ---------- Comunidade / Chat ----------
async function loadChat(type = state.activeChat) { state.activeChat = type; $('#chatForm').hidden = type === 'vip_noticias' && !isOwnerUser(); $('#messageList').innerHTML = '<div class="empty-state">Carregando conversa...</div>'; try { const data = await apiRequest(`/chat/${type}`); state.messages = Array.isArray(data) ? data : []; renderMessages(); } catch (error) { console.error('Falha ao carregar chat.', error); $('#messageList').innerHTML = '<div class="empty-state">Não foi possível carregar esta conversa agora.</div>'; } }
function renderMessages() { $('#messageList').innerHTML = state.messages.length ? state.messages.map(message => `<div class="message" data-message-id="${escapeHtml(message.id)}"><strong>${escapeHtml(message.profiles?.nome || 'Leitor Gutenberg')}</strong><time>${formatDate(message.created_at)}</time><p>${escapeHtml(message.conteudo)}${isOwnerUser() ? ` <button type="button" class="remove-item" data-message-remove="${escapeHtml(message.id)}">Remover</button>` : ''}</p></div>`).join('') : '<div class="empty-state">Ainda não há mensagens. Comece a conversa.</div>'; }
async function submitMessage(event) { event.preventDefault(); if (!state.user?.id) { toast('Entre na sua conta para conversar.'); location.hash = '#login'; return; } try { await apiRequest('/chat/enviar', { method: 'POST', body: JSON.stringify({ conteudo: $('#chatMessage').value, tipo_chat: state.activeChat }) }); $('#chatMessage').value = ''; await loadChat(); } catch (error) { console.error('Falha ao enviar mensagem.', error); toast(error.message || 'Não foi possível enviar a mensagem.'); } }

// ---------- Chat de pedido (funcionário fala com quem pediu) ----------
async function openPedidoChat(pedidoId, titulo) { state.activePedidoId = pedidoId; $('#orderChatTitle').textContent = titulo || 'Pedido'; $('#orderMessageList').innerHTML = '<div class="empty-state">Carregando conversa...</div>'; $('#orderChatModal').showModal(); try { const data = await apiRequest(`/chat/pedido?pedido_id=${encodeURIComponent(pedidoId)}`); renderOrderMessages(Array.isArray(data) ? data : []); } catch (error) { console.error('Falha ao carregar conversa do pedido.', error); $('#orderMessageList').innerHTML = '<div class="empty-state">Não foi possível carregar esta conversa.</div>'; } }
function renderOrderMessages(messages) { $('#orderMessageList').innerHTML = messages.length ? messages.map(message => `<div class="message"><strong>${escapeHtml(message.profiles?.nome || 'Leitor Gutenberg')}</strong><time>${formatDate(message.created_at)}</time><p>${escapeHtml(message.conteudo)}</p></div>`).join('') : '<div class="empty-state">Ainda não há mensagens sobre este pedido.</div>'; }
async function submitOrderMessage(event) { event.preventDefault(); if (!state.activePedidoId) return; try { await apiRequest('/chat/enviar', { method: 'POST', body: JSON.stringify({ conteudo: $('#orderChatMessage').value, tipo_chat: 'pedido', pedido_id: state.activePedidoId }) }); $('#orderChatMessage').value = ''; const data = await apiRequest(`/chat/pedido?pedido_id=${encodeURIComponent(state.activePedidoId)}`); renderOrderMessages(Array.isArray(data) ? data : []); } catch (error) { console.error('Falha ao enviar mensagem do pedido.', error); toast(error.message || 'Não foi possível enviar a mensagem.'); } }

// ---------- Meus pedidos (cliente) ----------
async function loadMeusPedidos() { if (!state.user?.id) return; try { state.meusPedidos = await apiRequest('/pedidos/meus'); renderMeusPedidos(); } catch (error) { console.error('Falha ao carregar pedidos.', error); } }
function renderMeusPedidos() { const target = $('#myOrdersList'); if (!target) return; target.innerHTML = state.meusPedidos.length ? state.meusPedidos.map(pedido => `<div class="admin-row"><div><strong>Pedido de ${formatDate(pedido.created_at)}</strong><small>${(pedido.pedido_itens || []).map(i => i.produtos?.titulo || 'item').join(', ')} · ${formatPrice(pedido.total)} · status: ${escapeHtml(pedido.status)}</small></div><button class="mini-button" data-order-chat="${escapeHtml(pedido.id)}">Falar com a loja</button></div>`).join('') : '<div class="empty-state">Você ainda não fez nenhum pedido.</div>'; }

// ---------- Diário de leitura (com trechos públicos) ----------
async function loadPublicDiaries() { try { const data = await apiRequest('/diario/comunidade/publicos'); state.diaries = Array.isArray(data) ? data : []; $('#publicDiaryList').innerHTML = state.diaries.length ? state.diaries.slice(0, 3).map(diary => `<div class="diary-entry"><h3>${escapeHtml(diary.livro_titulo || 'Leitura em andamento')}</h3>${diary.privacidade === 'parcial' ? (diary.trechos || []).map(t => `<p>${escapeHtml(t.texto)}</p>`).join('') || '<p class="muted">Sem trechos públicos ainda.</p>' : `<p>${escapeHtml(diary.anotacoes || 'Uma leitura compartilhada pela comunidade.')}</p>`}<small>${escapeHtml(diary.profiles?.nome || 'Leitor')} · ${escapeHtml(diary.privacidade)}</small></div>`).join('') : '<div class="empty-state">A comunidade ainda não publicou diários.</div>'; } catch (error) { console.error('Falha ao carregar diários públicos.', error); $('#publicDiaryList').innerHTML = '<div class="empty-state">Diários indisponíveis no momento.</div>'; } }
function renderTrechosBuilder() { $('#diaryTrechosBuilder').hidden = $('#diaryPrivacy').value !== 'parcial'; $('#diaryTrechosList').innerHTML = state.trechos.map((texto, index) => `<div class="form-row" style="align-items:center"><input data-trecho-index="${index}" value="${escapeHtml(texto)}" placeholder="Um trecho que pode ficar público"><button type="button" class="remove-item" data-trecho-remove="${index}">Remover</button></div>`).join(''); }
async function submitDiary(event) { event.preventDefault(); if (!state.user?.id) { toast('Entre na sua conta para salvar seu diário.'); location.hash = '#login'; return; } const privacidade = $('#diaryPrivacy').value; const trechos = privacidade === 'parcial' ? state.trechos.filter(Boolean).map(texto => ({ texto, publico: true })) : []; try { const data = await apiRequest('/diario', { method: 'POST', body: JSON.stringify({ livro_titulo: $('#diaryBook').value, data_inicio: $('#diaryStart').value, data_fim: $('#diaryEnd').value, anotacoes: `${$('#diaryProgress').value}% — ${$('#diaryNotes').value}`, privacidade, trechos }) }); state.diaries.unshift(data.diario || data); renderUserDiaries(); toast('Anotação criada com sucesso.'); $('#diaryForm').reset(); $('#progressOutput').textContent = '0%'; state.trechos = []; renderTrechosBuilder(); } catch (error) { console.error('Falha ao salvar diário.', error); toast(error.message || 'Não foi possível salvar a anotação.'); } }
function renderUserDiaries() { const own = state.diaries.filter(item => item.usuario_id === state.user?.id); $('#diaryList').innerHTML = own.length ? own.map(diary => `<div class="diary-entry"><h3>${escapeHtml(diary.livro_titulo)}</h3><p>${escapeHtml(diary.anotacoes || '')}</p><small>${formatDate(diary.data_inicio)} ${diary.data_fim ? `→ ${formatDate(diary.data_fim)}` : ''} · ${escapeHtml(diary.privacidade)}${diary.privacidade === 'parcial' ? ` (${(diary.trechos || []).length} trecho(s) público(s))` : ''}</small></div>`).join('') : '<div class="empty-state">Suas próximas leituras aparecerão aqui.</div>'; }
function renderPlans() { $('#planGrid').innerHTML = Object.entries(VIP_PLANS).map(([key, plan]) => `<article class="plan-card ${plan.featured ? 'featured' : ''}">${plan.featured ? '<span class="plan-label">Mais escolhido</span>' : ''}<h3>${plan.name}</h3><p>${plan.description}</p><strong class="price">R$ ${plan.price}<small>/mês</small></strong><ul>${plan.benefits.map(item => `<li>${item}</li>`).join('')}</ul><button class="button ${plan.featured ? 'primary' : 'secondary'}" data-plan="${key}">Assinar plano</button></article>`).join(''); }

// ---------- Painel administrativo ----------
// Regras (batendo com o pedido da cliente):
//  - funcionário: só mexe em promoção de produtos e conversa sobre pedidos.
//  - dona/admin: tudo que o funcionário faz + estoque geral, cadastro de
//    produto/combo completo, gestão de equipe, chat VIP e moderação do
//    chat livre / avaliações.
function adminRole() { return String(state.user?.tipo_usuario || '').toLowerCase(); }
function isAdminRole(role) { return ['funcionario', 'dona', 'admin'].includes(String(role || '').toLowerCase()); }
function isAdminUser() { return isAdminRole(adminRole()); }
function isOwnerUser() { return ['dona', 'admin'].includes(adminRole()); }
function adminRoleLabel(role) { return ['dona', 'admin'].includes(String(role || '').toLowerCase()) ? 'dona' : 'funcionário'; }
function renderAdmin() {
  const nav = $('#adminNav');
  nav.hidden = !isAdminUser();
  if (!isAdminUser()) { $('#adminPanel').innerHTML = '<div class="admin-grid" id="adminGrid"><div class="empty-state">Esta área é reservada para funcionários e dona da loja.</div></div>'; return; }
  const owner = isOwnerUser();
  $('#adminPanel').innerHTML = '<div class="admin-panel-head"><span>Permissão atual: <strong>' + escapeHtml(adminRoleLabel(adminRole())) + '</strong></span><button class="button secondary" type="button" data-admin-logout>Sair</button></div><div class="admin-grid" id="adminGrid"></div>';
  const metrics = state.adminMetrics || {};
  const cards = [['Produtos', metrics.produtos ?? state.books.length + state.stationery.length], ['Mensagens', metrics.mensagens ?? state.messages.length], ['Avaliações', metrics.avaliacoes ?? state.reviews.length]];
  $('#adminGrid').innerHTML = cards.map(([label, value]) => `<div class="admin-card"><strong>${value}</strong><span>${label}</span></div>`).join('');

  // Painel do FUNCIONÁRIO: só promoção + pedidos pra conversar com clientes.
  let html = `<div class="admin-tools"><div class="admin-list"><h3>Promoções</h3><form class="form-card" id="promoForm"><label>Produto<select name="produto_id" id="promoProductSelect"></select></label><label class="check-line"><input type="checkbox" name="promocao" id="promoActive"> Em promoção</label><label>Preço antigo (De:)<input name="preco_antigo" id="promoOldPrice" type="number" step="0.01" min="0"></label><button class="button primary" type="submit">Salvar promoção</button></form><p class="muted" style="font-size:11px">Funcionário só altera promoção — não cria, edita ou apaga produtos.</p></div><div class="admin-list"><h3>Pedidos para atender</h3><div id="adminOrdersList"><div class="empty-state">Carregando pedidos...</div></div></div></div>`;

  if (owner) {
    html += `<div class="admin-tools"><form class="form-card" id="adminProductForm"><h3>Adicionar produto</h3><label>Título<input name="titulo" required></label><label>Descrição<textarea name="descricao" rows="3"></textarea></label><div class="form-row"><label>Preço<input name="preco" type="number" step="0.01" min="0" required></label><label>Categoria<select name="categoria"><option value="livro">Livro</option><option value="papelaria">Papelaria</option></select></label></div><label>Gênero<input name="genero"></label><label>Imagem (URL)<input name="imagem" type="url" placeholder="https://..."></label><label>Estoque<input name="estoque" type="number" min="0" value="0"></label><label class="check-line"><input type="checkbox" name="is_combo"> É um combo/kit</label><button class="button primary" type="submit">Adicionar produto</button></form><div class="admin-list"><h3>Produtos cadastrados</h3><div id="adminProductList"><div class="empty-state">Carregando produtos...</div></div></div></div>`;
    html += `<div class="admin-tools"><div class="admin-list"><h3>Estoque</h3><div id="adminStockList"><div class="empty-state">Carregando estoque...</div></div></div><div class="admin-list"><h3>Funcionários e permissões</h3><form id="employeeForm" class="form-card"><label>Nome<input name="nome" required></label><label>E-mail<input name="email" type="email" required></label><label>Senha<input name="password" type="password" minlength="6" required></label><label>Permissão<select name="tipo_usuario"><option value="funcionario">Funcionário</option><option value="dona">Dona</option><option value="admin">Administradora</option></select></label><button class="button primary" type="submit">Adicionar funcionário</button></form><div id="employeeList"><div class="empty-state">Carregando equipe...</div></div></div></div>`;
    html += `<div class="admin-tools"><div class="admin-list"><h3>Chat VIP</h3><form id="vipMessageForm" class="form-card"><label>Mensagem<textarea name="conteudo" rows="4" required maxlength="500"></textarea></label><button class="button primary" type="submit">Enviar notícia VIP</button></form></div><div class="admin-list"><h3>Composição de combos</h3><form class="form-card" id="comboForm"><label>Combo<select name="combo_id" id="comboProductSelect"></select></label><label>Itens (um por linha: id do produto x quantidade)<textarea name="itens" id="comboItensInput" rows="4" placeholder="ex: 3f2e...-id x 1"></textarea></label><button class="button primary" type="submit">Salvar composição</button></form><p class="muted" style="font-size:11px">Cole o ID do produto (visível na lista de produtos cadastrados) — estrutural, por isso é só da dona.</p></div></div>`;
    html += `<div class="admin-tools"><div class="admin-list"><h3>Moderação — Chat livre</h3><p class="muted" style="font-size:12px">Abra a aba <a class="text-link" href="#comunidade">Comunidade</a> e use "Remover" em cada mensagem.</p></div><div class="admin-list"><h3>Moderação — Avaliações</h3><p class="muted" style="font-size:12px">Abra um produto e use "Remover" em cada avaliação. Só dona/admin veem esse botão.</p></div></div>`;
  }

  $('#adminPanel').insertAdjacentHTML('beforeend', html);
  renderAdminProducts();
  populatePromoSelect();
  loadAdminOrders();
  if (owner) { renderAdminStock(); renderEmployees(); populateComboSelect(); }
}
function populatePromoSelect() { const select = $('#promoProductSelect'); if (!select) return; const list = state.adminProducts || []; select.innerHTML = list.map(p => `<option value="${escapeHtml(p.id)}">${escapeHtml(p.titulo)}${p.promocao ? ' (em promoção)' : ''}</option>`).join(''); select.addEventListener('change', fillPromoForm); if (list.length) fillPromoForm(); }
function fillPromoForm() { const select = $('#promoProductSelect'); const product = (state.adminProducts || []).find(p => String(p.id) === select.value); if (!product) return; $('#promoActive').checked = Boolean(product.promocao); $('#promoOldPrice').value = product.preco_antigo || ''; }
function populateComboSelect() { const select = $('#comboProductSelect'); if (!select) return; const combos = (state.adminProducts || []).filter(p => p.is_combo); select.innerHTML = combos.length ? combos.map(p => `<option value="${escapeHtml(p.id)}">${escapeHtml(p.titulo)}</option>`).join('') : '<option value="">Nenhum combo cadastrado ainda</option>'; }
async function loadAdminOrders() { const target = $('#adminOrdersList'); if (!target) return; try { state.adminPedidos = await apiRequest('/pedidos'); target.innerHTML = state.adminPedidos.length ? state.adminPedidos.map(pedido => `<div class="admin-row"><div><strong>${escapeHtml(pedido.profiles?.nome || 'Cliente')}</strong><small>${(pedido.pedido_itens || []).map(i => i.produtos?.titulo || 'item').join(', ')} · ${formatPrice(pedido.total)}</small></div>${isOwnerUser() ? `<select data-order-status="${escapeHtml(pedido.id)}"><option value="pendente" ${pedido.status === 'pendente' ? 'selected' : ''}>Pendente</option><option value="preparando" ${pedido.status === 'preparando' ? 'selected' : ''}>Preparando</option><option value="enviado" ${pedido.status === 'enviado' ? 'selected' : ''}>Enviado</option><option value="entregue" ${pedido.status === 'entregue' ? 'selected' : ''}>Entregue</option><option value="cancelado" ${pedido.status === 'cancelado' ? 'selected' : ''}>Cancelado</option></select>` : `<span class="muted" style="font-size:12px">${escapeHtml(pedido.status)}</span>`}<button class="mini-button" data-order-chat="${escapeHtml(pedido.id)}">Conversar</button></div>`).join('') : '<div class="empty-state">Nenhum pedido no momento.</div>'; } catch (error) { console.error('Falha ao carregar pedidos administrativos.', error); target.innerHTML = '<div class="empty-state">Não foi possível carregar os pedidos.</div>'; } }
function renderAdminProducts() { const list = state.adminProducts || []; const target = $('#adminProductList'); if (!target) return; target.innerHTML = list.length ? list.map(product => `<div class="admin-row"><div><strong>${escapeHtml(product.titulo)}</strong><small>${escapeHtml(product.id)} · ${escapeHtml(product.categoria)} · ${formatPrice(product.preco)}</small></div><form data-product-edit="${escapeHtml(product.id)}"><input name="preco" type="number" step="0.01" min="0" value="${Number(product.preco) || 0}" aria-label="Preço de ${escapeHtml(product.titulo)}"><button class="mini-button">Salvar</button><button type="button" class="remove-item" data-product-remove="${escapeHtml(product.id)}">Remover</button></form></div>`).join('') : '<div class="empty-state">Nenhum produto cadastrado.</div>'; }
function renderAdminStock() { const target = $('#adminStockList'); if (!target) return; const list = state.adminProducts || []; target.innerHTML = list.length ? list.map(product => `<form class="admin-row" data-stock-edit="${escapeHtml(product.id)}"><div><strong>${escapeHtml(product.titulo)}</strong><small>${Number(product.estoque) === 0 ? 'Sem estoque' : Number(product.estoque) <= 5 ? 'Estoque baixo' : 'Disponível'}</small></div><input name="estoque" type="number" min="0" value="${Number(product.estoque) || 0}" aria-label="Estoque de ${escapeHtml(product.titulo)}"><button class="mini-button">Atualizar</button></form>`).join('') : '<div class="empty-state">Nenhum produto cadastrado.</div>'; }
function renderEmployees() { const target = $('#employeeList'); if (!target) return; const list = state.employees || []; target.innerHTML = list.length ? list.map(employee => `<div class="admin-row"><div><strong>${escapeHtml(employee.nome || employee.email || 'Usuário')}</strong><small>${escapeHtml(employee.email || '')}</small></div><select data-role-edit="${escapeHtml(employee.id)}"><option value="funcionario" ${employee.tipo_usuario === 'funcionario' ? 'selected' : ''}>Funcionário</option><option value="dona" ${employee.tipo_usuario === 'dona' ? 'selected' : ''}>Dona</option><option value="admin" ${employee.tipo_usuario === 'admin' ? 'selected' : ''}>Administradora</option></select><button type="button" class="remove-item" data-employee-remove="${escapeHtml(employee.id)}">Remover</button></div>`).join('') : '<div class="empty-state">Nenhum funcionário cadastrado.</div>'; }
async function loadAdminData() { if (!isAdminUser()) return; try { const [metrics, products] = await Promise.all([apiRequest('/admin/dashboard'), apiRequest('/admin/produtos')]); state.adminMetrics = metrics; state.adminProducts = products; if (isOwnerUser()) state.employees = await apiRequest('/admin/funcionarios'); renderAdmin(); } catch (error) { console.error('Falha ao carregar painel administrativo.', error); toast(error.message || 'Não foi possível carregar o painel.'); } }
async function handleAdminSubmit(event) {
  const form = event.target; if (!form.closest('#adminPanel')) return; event.preventDefault();
  try {
    if (form.id === 'promoForm') { const body = Object.fromEntries(new FormData(form)); const produtoId = body.produto_id; await apiRequest(`/produtos/${encodeURIComponent(produtoId)}/promocao`, { method: 'PATCH', body: JSON.stringify({ promocao: form.promocao.checked, preco_antigo: body.preco_antigo ? Number(body.preco_antigo) : null }) }); toast('Promoção atualizada com sucesso.'); }
    else if (form.id === 'adminProductForm') { const body = Object.fromEntries(new FormData(form)); body.preco = Number(body.preco); body.estoque = Number(body.estoque || 0); body.is_combo = form.is_combo.checked; await apiRequest('/produtos', { method: 'POST', body: JSON.stringify(body) }); toast('Produto adicionado com sucesso.'); }
    else if (form.id === 'employeeForm') { await apiRequest('/admin/funcionarios', { method: 'POST', body: JSON.stringify(Object.fromEntries(new FormData(form))) }); toast('Funcionário adicionado com sucesso.'); }
    else if (form.id === 'vipMessageForm') { await apiRequest('/admin/chat-vip', { method: 'POST', body: JSON.stringify(Object.fromEntries(new FormData(form))) }); toast('Notícia VIP enviada com sucesso.'); }
    else if (form.id === 'comboForm') { const comboId = $('#comboProductSelect').value; const linhas = $('#comboItensInput').value.split('\n').map(l => l.trim()).filter(Boolean).map(linha => { const [produto_id, quantidade] = linha.split('x').map(s => s.trim()); return { produto_id, quantidade: Number(quantidade || 1) }; }); await apiRequest(`/produtos/${encodeURIComponent(comboId)}/combo-itens`, { method: 'PUT', body: JSON.stringify({ itens: linhas }) }); toast('Composição do combo salva com sucesso.'); }
    else if (form.dataset.productEdit) { const body = Object.fromEntries(new FormData(form)); body.preco = Number(body.preco); await apiRequest(`/produtos/${encodeURIComponent(form.dataset.productEdit)}`, { method: 'PATCH', body: JSON.stringify(body) }); toast('Produto atualizado com sucesso.'); }
    else if (form.dataset.stockEdit) { const body = { estoque: Number(new FormData(form).get('estoque')) }; await apiRequest(`/admin/estoque/${encodeURIComponent(form.dataset.stockEdit)}`, { method: 'PATCH', body: JSON.stringify(body) }); toast('Estoque atualizado com sucesso.'); }
    else return;
    await loadAdminData();
  } catch (error) { console.error('Falha em operação administrativa.', error); toast(error.message || 'Operação não realizada.'); }
}
async function handleAdminClick(event) {
  const orderChatButton = event.target.closest('[data-order-chat]'); if (orderChatButton) { const pedido = (state.adminPedidos.find(p => p.id === orderChatButton.dataset.orderChat)) || (state.meusPedidos.find(p => p.id === orderChatButton.dataset.orderChat)); openPedidoChat(orderChatButton.dataset.orderChat, pedido ? `Pedido de ${pedido.profiles?.nome || 'você'}` : 'Pedido'); return; }
  const reviewRemove = event.target.closest('[data-review-remove]'); if (reviewRemove) { try { await apiRequest(`/avaliacoes/${encodeURIComponent(reviewRemove.dataset.reviewRemove)}`, { method: 'DELETE' }); toast('Avaliação removida.'); await loadReviews(state.selectedProduct.id); } catch (error) { toast(error.message || 'Não foi possível remover a avaliação.'); } return; }
  const messageRemove = event.target.closest('[data-message-remove]'); if (messageRemove) { try { await apiRequest(`/chat/${encodeURIComponent(messageRemove.dataset.messageRemove)}`, { method: 'DELETE' }); toast('Mensagem removida.'); await loadChat(); } catch (error) { toast(error.message || 'Não foi possível remover a mensagem.'); } return; }
  const button = event.target.closest('[data-admin-logout], [data-product-remove], [data-employee-remove]'); if (!button) return;
  if (button.dataset.adminLogout !== undefined) { state.user = null; localStorage.removeItem(STORAGE_KEYS.user); localStorage.removeItem(STORAGE_KEYS.session); $('#adminLoginForm').reset(); updateAccount(); toast('Sessão administrativa encerrada.'); location.hash = '#home'; return; }
  try { if (button.dataset.productRemove) { await apiRequest(`/produtos/${encodeURIComponent(button.dataset.productRemove)}`, { method: 'DELETE' }); toast('Produto removido com sucesso.'); } else if (button.dataset.employeeRemove) { await apiRequest(`/admin/funcionarios/${encodeURIComponent(button.dataset.employeeRemove)}`, { method: 'DELETE' }); toast('Funcionário removido com sucesso.'); } await loadAdminData(); } catch (error) { console.error('Falha em operação administrativa.', error); toast(error.message || 'Operação não realizada.'); }
}
async function handleAdminChange(event) {
  const roleSelect = event.target.closest('[data-role-edit]'); if (roleSelect) { try { await apiRequest(`/admin/funcionarios/${encodeURIComponent(roleSelect.dataset.roleEdit)}/permissao`, { method: 'PATCH', body: JSON.stringify({ tipo_usuario: roleSelect.value }) }); toast('Permissão atualizada com sucesso.'); await loadAdminData(); } catch (error) { console.error('Falha em operação administrativa.', error); toast(error.message || 'Operação não realizada.'); } return; }
  const statusSelect = event.target.closest('[data-order-status]'); if (statusSelect) { try { await apiRequest(`/pedidos/${encodeURIComponent(statusSelect.dataset.orderStatus)}/status`, { method: 'PATCH', body: JSON.stringify({ status: statusSelect.value }) }); toast('Status do pedido atualizado.'); await loadAdminOrders(); } catch (error) { toast(error.message || 'Não foi possível atualizar o status.'); } }
}
function setupAdminEvents() { document.addEventListener('submit', handleAdminSubmit); document.addEventListener('click', handleAdminClick); document.addEventListener('change', handleAdminChange); }

// ---------- Navegação / eventos gerais ----------
function navigate() { const id = location.hash.slice(1) || 'home'; if (id === 'admin' && !isAdminUser()) { toast('Acesso restrito ao painel administrativo.'); location.hash = '#home'; return; } const target = $(`#${CSS.escape(id)}`) || $('#home'); $$('[data-page]').forEach(section => section.classList.toggle('active', section === target)); $$('.main-nav a').forEach(link => link.classList.toggle('active', link.hash === `#${target.id}`)); $('#mainNav').classList.remove('open'); if (target.id === 'comunidade') { const vipTab = $('[data-chat-tab="vip_noticias"]'); if (vipTab) vipTab.hidden = adminRole() === 'funcionario'; loadChat(); loadPublicDiaries(); } if (target.id === 'perfil') { updateAccount(); loadMeusPedidos(); } if (target.id === 'admin') { renderAdmin(); loadAdminData(); } window.scrollTo({ top: 0, behavior: 'smooth' }); }
function setupEvents() {
  window.addEventListener('hashchange', navigate);
  $('#menuToggle').addEventListener('click', () => { const open = $('#mainNav').classList.toggle('open'); $('#menuToggle').setAttribute('aria-expanded', String(open)); });
  $('#adminButton').addEventListener('click', () => { if (isAdminUser()) location.hash = '#admin'; else $('#adminLoginModal').showModal(); });
  $('#closeAdminLogin').addEventListener('click', () => $('#adminLoginModal').close());
  $('#adminLoginForm').addEventListener('submit', submitAdminLogin);
  $('#cartButton').addEventListener('click', openCart);
  $('#closeCart').addEventListener('click', closeCart);
  $('#drawerOverlay').addEventListener('click', closeCart);
  $('#closeModal').addEventListener('click', () => $('#productModal').close());
  $('#closePreview').addEventListener('click', () => $('#previewModal').close());
  $('#closeOrderChat').addEventListener('click', () => $('#orderChatModal').close());
  $('#orderChatForm').addEventListener('submit', submitOrderMessage);
  $('#logoutButton').addEventListener('click', () => { state.user = null; localStorage.removeItem(STORAGE_KEYS.user); localStorage.removeItem(STORAGE_KEYS.session); updateAccount(); toast('Você saiu da sua conta.'); location.hash = '#home'; });
  $('#searchForm').addEventListener('submit', event => { event.preventDefault(); const term = $('#globalSearch').value.trim(); $('#bookSearch').value = term; location.hash = '#livraria'; renderBooks(); });
  ['bookSearch', 'bookGenre', 'bookFormat', 'bookPromo', 'bookSort'].forEach(id => $(`#${id}`).addEventListener('input', renderBooks));
  $('#clearBookFilters').addEventListener('click', () => { $('#bookSearch').value = ''; $('#bookGenre').value = ''; $('#bookFormat').value = ''; $('#bookPromo').checked = false; renderBooks(); });
  $('#stationeryFilters').addEventListener('click', event => { const button = event.target.closest('button'); if (!button) return; $$('#stationeryFilters button').forEach(item => item.classList.toggle('active', item === button)); renderStationery(button.dataset.category); });
  document.addEventListener('click', event => {
    const productButton = event.target.closest('[data-product]'); if (productButton) openProduct(productButton.dataset.product);
    const addButton = event.target.closest('[data-add]'); if (addButton) { addToCart(addButton.dataset.add); $('#productModal').close(); }
    const previewButton = event.target.closest('[data-preview]'); if (previewButton) { const product = findProduct(previewButton.dataset.preview); $('#previewTitle').textContent = product.titulo; $('#previewText').textContent = product.amostra_primeira_pagina || 'Esta prévia demonstrativa ainda não possui texto cadastrado para este produto.'; $('#previewModal').showModal(); }
    const orderChatButton = event.target.closest('[data-order-chat]'); if (orderChatButton && !event.target.closest('#adminPanel')) { const pedido = state.meusPedidos.find(p => p.id === orderChatButton.dataset.orderChat); openPedidoChat(orderChatButton.dataset.orderChat, pedido ? `Pedido de ${formatDate(pedido.created_at)}` : 'Pedido'); }
    const quantity = event.target.closest('[data-quantity]'); if (quantity) { const item = state.cart.find(entry => entry.key === quantity.dataset.key); if (item) item.quantity += Number(quantity.dataset.quantity); state.cart = state.cart.filter(entry => entry.quantity > 0); saveStorage(STORAGE_KEYS.cart, state.cart); renderCart(); }
    const remove = event.target.closest('[data-remove]'); if (remove) { state.cart = state.cart.filter(item => item.key !== remove.dataset.remove); saveStorage(STORAGE_KEYS.cart, state.cart); renderCart(); }
    const plan = event.target.closest('[data-plan]'); if (plan) { if (!state.user) { toast('Crie sua conta para escolher um plano.'); location.hash = '#cadastro'; } else { toast(`Plano ${VIP_PLANS[plan.dataset.plan].name} selecionado. Finalize pelo cadastro ou perfil.`); } }
    const customize = event.target.closest('[data-customize]'); if (customize) { const product = state.selectedProduct; const customization = { cor: prompt('Cor desejada (opcional):') || '', nome: prompt('Nome na personalização (opcional):') || '' }; addToCart(product.id, customization); $('#productModal').close(); }
    const trechoRemove = event.target.closest('[data-trecho-remove]'); if (trechoRemove) { state.trechos.splice(Number(trechoRemove.dataset.trechoRemove), 1); renderTrechosBuilder(); }
  });
  $('#loginForm').addEventListener('submit', submitLogin);
  $('#registerForm').addEventListener('submit', submitRegister);
  $('#chatForm').addEventListener('submit', submitMessage);
  $$('[data-chat-load]').forEach(button => button.addEventListener('click', () => loadChat()));
  $$('.chat-tabs').forEach(tabs => tabs.addEventListener('click', event => { const tab = event.target.closest('[data-chat-tab]'); if (!tab) return; $$('.chat-tabs button').forEach(button => button.classList.toggle('active', button === tab)); loadChat(tab.dataset.chatTab); }));
  $('#diaryForm').addEventListener('submit', submitDiary);
  $('#diaryProgress').addEventListener('input', event => { $('#progressOutput').textContent = `${event.target.value}%`; });
  $('#diaryPrivacy').addEventListener('change', renderTrechosBuilder);
  $('#addTrechoButton').addEventListener('click', () => { state.trechos.push(''); renderTrechosBuilder(); });
  document.addEventListener('input', event => { const trechoInput = event.target.closest('[data-trecho-index]'); if (trechoInput) state.trechos[Number(trechoInput.dataset.trechoIndex)] = trechoInput.value; });
  $('#checkoutButton').addEventListener('click', checkout);
  $('#productModal').addEventListener('submit', async event => { if (!event.target.matches('#reviewForm')) return; event.preventDefault(); if (!state.user?.id) { toast('Entre na sua conta para enviar uma avaliação.'); return; } const [nota, comentario] = [...event.target.elements].filter(element => element.tagName === 'INPUT').map(element => element.value); try { await apiRequest('/avaliacoes', { method: 'POST', body: JSON.stringify({ produto_id: state.selectedProduct.id, comentario, nota: Number(nota) }) }); event.target.reset(); await loadReviews(state.selectedProduct.id); toast('Avaliação enviada com sucesso.'); } catch (error) { console.error('Falha ao enviar avaliação.', error); toast(error.message || 'Não foi possível enviar a avaliação.'); } });
}
async function init() { setupEvents(); setupAdminEvents(); renderPlans(); renderCart(); updateAccount(); navigate(); await loadProducts(); renderAdmin(); await loadAdminData(); loadPublicDiaries(); if (state.user?.id) loadMeusPedidos(); }
init();
